### ISSUE TITLE
Not changing value on the go

### ISSUE THREAD

**Issue by AlMel3000** [thegamenicorus/react-native-phone-input#1]
Hello!
**Here is a part of my code:**
`<PhoneInput ref = 'phone' cancelText = {'Cancel'} confirmText = {'Select'} autoFocus = {true} style = {{flexGrow: 1, height: 40, borderBottomColor: '#c98d41',padding: 8,borderBottomWidth: 2, marginHorizontal:33}} onChangePhoneNumber = {(text) =>  this._formatPhoneAndResetWarning(text)} initialCountry = 'ru' value={this.state.phone}/>`

**and here is method for changing state:**
```
`_formatPhoneAndResetWarning(phoneInput){`
        let phoneformatReactNative = require("phoneformat-react-native")
        let formattedPhone = phoneformatReactNative.formatInternational('RU', phoneInput);
        this.setState({
            phone: formattedPhone
        });
        console.log('formatted Number is: ', this.state.phone)
    `}`
```

So the state changes but PhoneInput's value - not

**Comment by thegamenicorus** [comment]
Hello @AlMel3000 

Could you please update react-native-phone-input to version 0.1.7 and try again.

Cheer!

**Comment by AlMel3000** [comment]
Well done!
Thank you for fast and perfect improvement!
