### ISSUE TITLE
Question: Is there any way to change the default country cca2 from the US?

### ISSUE THREAD

**Issue by rundlel** [thegamenicorus/react-native-phone-input#10]
We want to set it to be the users current location.

**Comment by thegamenicorus** [comment]
Have you try 'initialCountry'? 
[see doc](https://github.com/thegamenicorus/react-native-phone-input#configuration)

**Comment by thegamenicorus** [comment]
hi @rundlel,

If this problem still doesn't solved, feel free to reopen this issue.
