### ISSUE TITLE
Compatibility issue with react native 0.60

### ISSUE THREAD

**Issue by amit-esyfix** [thegamenicorus/react-native-phone-input#118]
Getting warnings while using it with react native 0.60: componentWillReceiveProps and componentWillMount deprecated

**Comment by Zakyyy** [comment]
we are waiting for the new release

**Comment by ciaoamigo** [comment]
News?

**Comment by yigithanyucedag** [comment]
Still same.

**Comment by amit-esyfix** [comment]
Updated the plugin. Waiting for it to be merged with master

**Comment by choudharyjji** [comment]
Warning: componentWillReceiveProps has been renamed, and is not recommended for use.

**Comment by jaydenwindle** [comment]
This should be fixed now that #122 has been merged. These changes will be in the next release.

**Comment by ahmedkotb** [comment]
is this still maintained ? this fix wasn't released till now (last release was 0.2.4 from 9 months ago, right ?)

**Comment by esdotzed** [comment]
When is the next release? Do I have to fork and keep my own copy????

**Comment by esdotzed** [comment]
@ahmedkotb Just do it yourself. I helped myself fixed it.
https://github.com/thegamenicorus/react-native-phone-input/commit/43d935639a7806b25a9fef15be6c9f6fcd8c88b4
