### ISSUE TITLE
How to use isValidNumber function?

### ISSUE THREAD

**Issue by lkum11** [thegamenicorus/react-native-phone-input#124]

**Comment by ayeshasaeed94** [comment]
<PhoneInput
          ref={(ref) => this.phone = ref}
          value={this.state.phone_number}
          onChangePhoneNumber={(number) => this.setState({phone_number: number})}
/>

in any function in that component you can write this.phone.isValidNumber()

**Comment by jaydenwindle** [comment]
@ayeshasaeed94 is correct - `isValidNumber` can be accessed using a `PhoneInput` ref. For an example of how to interact with `PhoneInput` via a ref, see the [Custom Picker](https://github.com/thegamenicorus/react-native-phone-input#custom-your-own-picker) section of the readme.

**Comment by usman1579** [comment]
but how we use in Hooks?
