### ISSUE TITLE
Invariant Violation: Invariant Violation: Function components cannot have refs. Did you mean to use React.forwardRef()?

### ISSUE THREAD

**Issue by Mnabawy** [thegamenicorus/react-native-phone-input#130]
here is my child component
`  render() {
    return (
      <View style={styles.container}>
        <PhoneInput
          phoneRef={ref => {
            this.phone = ref;
          }}
          onPressFlag={this.onPressFlag}
        />
      </View>
    );
  }
}`
here is my parent component 

`   <PhoneInput
                style={styles.phoneInput}
                ref="phone"
                onChangeText={handleChange("phoneInput")}
                onBlur={handleBlur("phoneInput")}
                placeholder="enter phone number"
                autoFocus
                offset={15}
              />`

**Comment by jaydenwindle** [comment]
Hey @Mnabawy! Can you please attach a full code sample? It's a little hard to tell what the issue is here from the info you provided. 

My initial guess is that your parent component is a functional component, so using the deprecated `ref="phone"` would cause this error. Have you tried using a callback ref on `PhoneInput` in your parent component?

**Comment by Mnabawy** [comment]
actually my question is how to use your package as a reusable component ?
with function component and hooks

**Comment by jaydenwindle** [comment]
Sure! Here's an example of using this package with a functional component and hooks:

```javascript
import React, { useRef, useState } from 'react';
import { Text, View } from 'react-native';

import PhoneInput from 'react-native-phone-input';

export default function App() {
  const [phoneValue, setPhoneValue] = useState(null)
  const [isValidNumber, setIsValidNumber] = useState(false)
  const phoneRef = useRef(undefined);

  return (
    <View>
      <PhoneInput
        ref={phoneRef}
        onChangePhoneNumber={value => {
          setPhoneValue(value);
          setIsValidNumber(phoneRef.current.isValidNumber())
        }} 
        placeholder="enter phone number" 
        autoFocus 
        offset={15} />
        <Text>Is Valid Number: {isValidNumber ? 'Yes' : 'No'}</Text>
    </View>
  );
}
```

You can see a working example here: https://snack.expo.io/@jaydenwindle/react-native-phone-input-ref-example

**Comment by Mnabawy** [comment]
what about using a custom example

**Comment by jaydenwindle** [comment]
@Mnabawy what do you mean by a custom example? Do you mean adding the hooks example to the readme? If so, feel free to submit a PR :)
