### ISSUE TITLE
npm version problem

### ISSUE THREAD

**Issue by Boubaker93** [thegamenicorus/react-native-phone-input#133]
Hello guys,

Please make sure to update the npm package. When i do `yarn add` i get the version without the fix of `componentWillMount` and `componentWillReceiveProps`. But when i got to the git directory i find that it got fixed.

Thank you guys in advance.

**Comment by jaydenwindle** [comment]
The npm package will be updated soon :) In the meantime you can install from `master` if you'd like to use the RN 0.60 changes right away.
