### ISSUE TITLE
NPM Package is wrong code, correct version number 0.1.9

### ISSUE THREAD

**Issue by brianhiss** [thegamenicorus/react-native-phone-input#14]
I got a prop-types warning on React Native 0.49.1, when I dug further, the react-native-phone-input library was throwing the error.

`npm` and `yarn` give the same issue. It says it's installed version 0.1.9, but when I look in the code, it's not consistent with the Git Repo here, where prop-types is fixed.

If you look at the package NPM/Yarn downloads, you can see the code is outdated:
https://registry.npmjs.org/react-native-phone-input/-/react-native-phone-input-0.1.9.tgz

`yarn add https://github.com/thegamenicorus/react-native-phone-input.git` fixes my issue, but wanted to let you know.

**Comment by albinekb** [comment]
`yarn add https://github.com/thegamenicorus/react-native-phone-input.git#c73d529bd71f63fab6e5d3442ba1571e9bb02749`
is better, that locks it to the current latest commit in master 👍

**Comment by thegamenicorus** [comment]
Hi,
sorry for any inconvenience. v 0.1.10 is already on npm.

**Comment by albinekb** [comment]
no problem 👍 thanks a lot ❤️  @thegamenicorus
