### ISSUE TITLE
PhoneInput is just showing country flag but not showing country code.

### ISSUE THREAD

**Issue by nisarmalhi** [thegamenicorus/react-native-phone-input#145]

**Comment by dihan** [comment]
Yeah same issue

**Comment by nisarmalhi** [comment]
My issue was resolved by downgrading react-native-number-input to 0.2.2 version.

**Comment by AndriiBoiko** [comment]
Hey!
Got the same.
Are any updates?

**Comment by aleks-plusplus** [comment]
I faced same issue. I tried to download react-native-phone-input version to 0.2.2, but it didn't work.
