### ISSUE TITLE
Hangup on RN0.47.0

### ISSUE THREAD

**Issue by neilakoh** [thegamenicorus/react-native-phone-input#15]
When installing the package on RN0.47.0 the app hangs up. This may be because of the PropType. The package is still using

import React, {
  Component,
  PropTypes,
} from 'react'

while on the latest version of RN it is now separated.

import PropTypes from 'prop-types';

**Comment by piotrgorecki** [comment]
On RN 0.49 I receive:

> Cannot read property 'string' of undefined
> <unknown>
>     countryPicker.js:21:25
> loadModuleImplementation
>     require.js:178:4

But the reason is the same, `PropTypes`.

**Comment by abuinitski** [comment]
Fixed by 1f858b9f53cba6a6e0a24e1289e3e81f41c079ec but not in npm (and package version was not updated).

Use master branch.

**Comment by thegamenicorus** [comment]
Hi,
sorry for any inconvenience. v 0.1.10 is already on npm.
