### ISSUE TITLE
Limit country list to one of several countries?

### ISSUE THREAD

**Issue by arrkaye** [thegamenicorus/react-native-phone-input#16]
I don't need the entire list..

Is it possible to pass in an array of countries to show in the picker? E.g. us, gb, fr

**Comment by HasanAlyazidi** [comment]
Check out my fork #29

[](https://github.com/HasanAlyazidi/react-native-phone-input/#custom-countries)

**Comment by thegamenicorus** [comment]
Hi @HasanAlyazidi ,

Thanks for you PR. veryawesome.

**Comment by HasanAlyazidi** [comment]
My pleasure

**Comment by affanhashone** [comment]
I am passing array to countries list, app is getting crash

**Comment by HasanAlyazidi** [comment]
Can you share your code?

**Comment by affanhashone** [comment]
this.state = {
countriesList : ['us']
} 
<PhoneInput ref={(ref) => { this.phone = ref; }}
                                countriesList = {this.state.countriesList}
                                autoFormat = {true}
                                textStyle = {{color: '#fff',fontSize:scale(13)}}
                                />

**Comment by affanhashone** [comment]
@HasanAlyazidi   Thanks Brother for Such a Quick Reply, I figure out, I am passing the Json list to countriesList props. Thanks

**Comment by ReactCoder12** [comment]
How can I limit countries to one country Please explain How this possible
