### ISSUE TITLE
No onSubmitEditing action or event?

### ISSUE THREAD

**Issue by evanjmg** [thegamenicorus/react-native-phone-input#21]
Is there anyway for the use to confirm that they are done typing the number?

**Comment by andwaal** [comment]
You got two options, use the _textComponent_ props and pass your own _TextInput_ element or you can use the _textProps_ where you can pass down the onSubmit event:

```
   textProps={{
            returnKeyType: "done",
            onSubmitEditing: () => console.log("onSubmit")
          }}
```
