### ISSUE TITLE
How to get country code

### ISSUE THREAD

**Issue by abhinavsk90** [thegamenicorus/react-native-phone-input#24]
If someone is typing the number with country code, I would like to get the country object using which you used to update the flag.

How can i achieve that.

**Comment by RoyalDeveloper2015** [comment]
I want to get country code from this too.

**Comment by honzababarik** [comment]
I am doing this:
```
getCountryCode = (iso) => {
    const countries = this.refs.phone.getAllCountries()
    for (let i = 0; i < countries.length; i++) {
      if (countries[i].iso2 === iso) {
        return countries[i].dialCode
      }
    }
  }
```

**Comment by abhishekush** [comment]
You can get country code using getDialCode() method from component refs

**Comment by dbelchev** [comment]
@abhishekush getDialCode returnes country DIAL code as '+1', but you can't directly obtain the country code as 'us', because the documented "getCountryCode" function is not a method of the reference. (I check the code, there isn't such function anywhere).
@thegamenicorus can you help with this one?

**Comment by thegamenicorus** [comment]
Hi all,

v 0.2.1, you can use .getISOCode() to get country code as 'us', 'ca' and etc.
