### ISSUE TITLE
There is no disable for TextInput and CountrySelect by default

### ISSUE THREAD

**Issue by allmaxgit** [thegamenicorus/react-native-phone-input#30]
With my project I need to disable component with certain conditions, but component have no this prop by default. I think, you should add prop `editable` for component, which disable onPress for CountryPicker and makes TextInput uneditable.
Now I can do it only with props 
```jsx
onPressFlag={() => false}
textProps={{ editable: false }}
```
for PhoneInput component, but it's crutch!

**Comment by gaston4930** [comment]
Thank you i was looking for that

**Comment by thegamenicorus** [comment]
Hi all,

`disabled` was added in v 0.2.0

thanks for your request.
