### ISSUE TITLE
this.phone.getPickerData()

### ISSUE THREAD

**Issue by karunkumark** [thegamenicorus/react-native-phone-input#32]
I am Getting undefined in the code

**Comment by Ketn** [comment]
I believe it should be `this.refs.phone.getPickerData()`

**Comment by BaderSerhan** [comment]
doesn't work either

**Comment by Ketn** [comment]
My bad. It depends on how it's implemented in your code. Please post some code for us to diagnose the issue.

**Comment by BaderSerhan** [comment]
I fixed it by just adding an if clause ..
`    componentDidMount = () => {
        if (this.phone)
            this.setState({pickerData: this.phone.getPickerData()});
    }`

**Comment by BaderSerhan** [comment]
i fixed it by just adding an if clause ...
`
componentDidMount = () => {
        if (this.phone)
            this.setState({pickerData: this.phone.getPickerData()});
    }
`
