### ISSUE TITLE
StyleSheet not supported

### ISSUE THREAD

**Issue by davidgoli** [thegamenicorus/react-native-phone-input#35]
I'm using ReactNative's `StyleSheet` to build styles, https://facebook.github.io/react-native/docs/stylesheet.html, which convert style objects into numerical ids that are used to look up the style from a global stylesheet. When using with this library, the styles are passed along just fine, but I get a warning: `Warning: Failed prop type: Invalid prop 'textStyle' of type 'number' supplied to 'PhoneInput', expected 'object'`.

This should be a fairly trivial fix, just updating the PropTypes to expect a number *or* an object should do the trick and get rid of the warning.

**Comment by emjayschoen** [comment]
This should also allow an array of styles e.g. `textStyle={[Styles.textStyle, Styles.customStyle]}`, which gives me the warning: `Warning: Failed prop type: Invalid prop 'textStyle' of type 'array' supplied to 'PhoneInput', expected 'object'`

**Comment by alorr10** [comment]
Using this line as the PropType for style and textStyle is working for me:

`PropTypes.oneOfType([
    PropTypes.object,
    PropTypes.number,
    PropTypes.arrayOf(PropTypes.object),
    PropTypes.arrayOf(PropTypes.number),
  ]),`

**Comment by vdlindenmark** [comment]
I've fixed this in this pull request:
https://github.com/thegamenicorus/react-native-phone-input/pull/66


You'll only get that error when using something like `const styles = StyleSheet.create`... My pull request fixed that issue
