### ISSUE TITLE
Could you please add the onBlur property in the Configuration? 

### ISSUE THREAD

**Issue by auchen** [thegamenicorus/react-native-phone-input#40]
This is an excellent project. It would be wonderful if you could add the onBlur configuration. Sometimes the phone number input field needs to be validated lively, e.g. length, numbers only, etc. Thanks very much.

**Comment by clementm916** [comment]
Was able to pass an `onBlur` callback using textProps which can be effective for any `TextInput` props:
```
 textProps={{ onBlur: () => { console.log("PHONE  BLUR") }, }}
```
