### ISSUE TITLE
Can't use onSubmitEditing prop

### ISSUE THREAD

**Issue by jandrell-formoso** [thegamenicorus/react-native-phone-input#42]
I can't make the PhoneInput focus on the next TextInput because it's not reading the onSubmitEditing prop that is visible on other react native inputs. Is there any fix to that? or some workaround? Thanks.

**Comment by clementm916** [comment]
Try passing it via `textProps`,which can be a list of objects that are  `TextInput` props or custom props incase of a custom `TextComponent`: 
```
 textProps={{ onSubmitEditing : () => { console.log("ON SUBMIT EDITING") }, }}
```

**Comment by jandrell-formoso** [comment]
@clementm916 Thank you! It's working now. 👍 💯
