### ISSUE TITLE
Can't focus phone input

### ISSUE THREAD

**Issue by DavitVosk** [thegamenicorus/react-native-phone-input#54]
Hi there.

I have some problem with focusing phone input when needed. My code is following:

`<PhoneInput
                  ref={ref => (this.phoneRef = ref)}
                  onChangePhoneNumber={this.handleMobileChange.bind(this)}
                />`

And when I call `this.phoneRef.focus()` I get undefined. Please help to find a solution. Thanks

**Comment by DavitVosk** [comment]
ok it worked. I was missing something in my code...

**Comment by xiurobert** [comment]
Hey could you tell me what exactly was missing in your code? I couldn't get mine to focus for some reason, even when I ran it in componentDidMount()

**Comment by DavitVosk** [comment]
@xiurobert I was calling `this.phoneRef.focus()` instead of `() => this.phoneRef.focus()`. Hope this will help you too

**Comment by xiurobert** [comment]
I'm trying to get it to focus in `componentDidMount()` but I'm failing to do so on iOS only. On android, it focuses completely fine.
