### ISSUE TITLE
autoFocus

### ISSUE THREAD

**Issue by Cyrus222** [thegamenicorus/react-native-phone-input#71]
would please add autoFocus?

**Comment by faisalbasha1982** [comment]
Auto Focus still not working

**Comment by Jose4gg** [comment]
`textProps` is available to pass props directly to the TextInput component, you can pass the `autoFocus` there.

> https://github.com/thegamenicorus/react-native-phone-input/blob/master/lib/index.js#L195

**Comment by pavel-genuine** [comment]
same issue here, keyboad showing up but no cursor showing.
