### ISSUE TITLE
Is there a way to focus the textcomponent in PhoneInput?

### ISSUE THREAD

**Issue by kevng9** [thegamenicorus/react-native-phone-input#8]
I've tried setting ref on Phoneinput but focus() does not seem to exist. Also tried passing ref into the TextComponent by using textProps = {{ref:'phoneInput'}} or textProps = {{ref='phoneInput'}}. Neither of which works.

Thanks

**Comment by lucaboieru** [comment]
I also ran into this issue and it would be really helpful to have the ```.focus()``` method just like ```<TextInput>```

**Comment by thegamenicorus** [comment]
please update to v 0.1.9, and you can use this code to focus on phone input

```jsx
componentDidMount() {
    this.refs.phone.focus()
}

render() {
    return(
        <PhoneInput ref='phone' style={{marginTop: 50}}/>
    );
}
```

**Comment by kevng9** [comment]
Awesome, this works perfectly. Thanks

**Comment by DavitVosk** [comment]
@kevng9 I have the same problem here. Can you please show me your code to see how you had fixed it. I use the logic of @thegamenicorus but it gives undefined. Thanks in advance

**Comment by DavitVosk** [comment]
Ah ok it worked...I was missing something in the code
