### ISSUE TITLE
Get PhoneInput value without ref, using onTextChange

### ISSUE THREAD

**Issue by latusdenis** [thegamenicorus/react-native-phone-input#87]
Hi! Is it possible to get PhoneInput value, using onTextChange, not refs?
```
<PhoneInput
    ref={(ref) => { this.phone = ref; }}
    onPressFlag={this.onPressFlag}
/>
```

Thanks!

**Comment by Valentinishe** [comment]
> Hi! Is it possible to get PhoneInput value, using onTextChange, not refs?
> 
> ```
> <PhoneInput
>     ref={(ref) => { this.phone = ref; }}
>     onPressFlag={this.onPressFlag}
> />
> ```
> Thanks!

But what this one `onChangePhoneNumber` did not suit you?

**Comment by latusdenis** [comment]
@Valentinishe Thanks a lot, it suits.

My bad, I didn't notice this method in docs

**Comment by BartoszKaszewczuk** [comment]
This issue can be closed now.
