### ISSUE TITLE
Flag icons dont show up

### ISSUE THREAD

**Issue by tkulpa** [thegamenicorus/react-native-phone-input#9]
There is only a gray rectangle
**react-native version**: 0.46.1
On Android device, using _react-native run-android_

Found out that commenting `resizeMode='stretch'` inside flag Image component fixes it

**Comment by overpink** [comment]
Same here

**Comment by thegamenicorus** [comment]
I'll check and release new version soon.

Thank you all.

**Comment by thegamenicorus** [comment]
resizeMode='stretch' was removed in v 0.1.9
